default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xbTweets_development

test:
  <<: *default
  database: xbTweets_test

production:
  <<: *default
  database: xbTweets_production
  username: xbTweets
  password: <%= ENV['XBTWEETS_DATABASE_PASSWORD'] %>
